services:
#  api-gateway:
#    build: ../deploy/api-gateway

  user-service:
    build:
      context: ../
      dockerfile: deploy/user-service/Dockerfile
    container_name: user-service
    ports:
      - "10000:10000" # grpc
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
#      redis:
#        condition: service_started
    volumes:
      - ../rsa_keys:/rsa_keys
    networks:
      - postgre
#      - redis

#  order-service:
#    build: ../deploy/order-service
#
#  payment-service:
#    build: ../deploy/payment-service
#
#  notification-service:
#    build: ../deploy/notification-service

  postgres:
    image: postgres:17-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ../.env
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgre

  goose:
    build: ../tools/goose
    container_name: goose
    depends_on:
      - postgres
    entrypoint: [ "/goose/entrypoint.sh" ]
    volumes:
      - ../migrations:/migrations
    env_file:
      - ../.env
    networks:
      - postgre

#  redis:
#    image: redis:7-alpine
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - redis

#  kafka:
#    image: bitnami/kafka:4.0.0
#    hostname: kafka
#    container_name: kafka
#    env_file:
#      - ../.env
#    healthcheck:
#      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#    volumes:
#      - kafka_data:/bitnami/kafka/data
#    networks:
#      - my-network

volumes:
  postgres_data:
  kafka_data:
#  redis_data:

networks:
  postgre:
#  redis: