// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/deimossy/order-processing-system/internal/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokenRepo creates a new instance of MockRefreshTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenRepo is an autogenerated mock type for the RefreshTokenRepo type
type MockRefreshTokenRepo struct {
	mock.Mock
}

type MockRefreshTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepo_Expecter {
	return &MockRefreshTokenRepo_Expecter{mock: &_m.Mock}
}

// GetByTokenHash provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) GetByTokenHash(ctx context.Context, token string) (*domain.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepo_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockRefreshTokenRepo_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRefreshTokenRepo_Expecter) GetByTokenHash(ctx interface{}, token interface{}) *MockRefreshTokenRepo_GetByTokenHash_Call {
	return &MockRefreshTokenRepo_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, token)}
}

func (_c *MockRefreshTokenRepo_GetByTokenHash_Call) Run(run func(ctx context.Context, token string)) *MockRefreshTokenRepo_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_GetByTokenHash_Call) Return(refreshToken *domain.RefreshToken, err error) *MockRefreshTokenRepo_GetByTokenHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepo_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.RefreshToken, error)) *MockRefreshTokenRepo_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUserId provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) RevokeAllByUserId(ctx context.Context, userId string) error {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUserId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepo_RevokeAllByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUserId'
type MockRefreshTokenRepo_RevokeAllByUserId_Call struct {
	*mock.Call
}

// RevokeAllByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockRefreshTokenRepo_Expecter) RevokeAllByUserId(ctx interface{}, userId interface{}) *MockRefreshTokenRepo_RevokeAllByUserId_Call {
	return &MockRefreshTokenRepo_RevokeAllByUserId_Call{Call: _e.mock.On("RevokeAllByUserId", ctx, userId)}
}

func (_c *MockRefreshTokenRepo_RevokeAllByUserId_Call) Run(run func(ctx context.Context, userId string)) *MockRefreshTokenRepo_RevokeAllByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_RevokeAllByUserId_Call) Return(err error) *MockRefreshTokenRepo_RevokeAllByUserId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepo_RevokeAllByUserId_Call) RunAndReturn(run func(ctx context.Context, userId string) error) *MockRefreshTokenRepo_RevokeAllByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByTokenHash provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) RevokeByTokenHash(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByTokenHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepo_RevokeByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByTokenHash'
type MockRefreshTokenRepo_RevokeByTokenHash_Call struct {
	*mock.Call
}

// RevokeByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRefreshTokenRepo_Expecter) RevokeByTokenHash(ctx interface{}, token interface{}) *MockRefreshTokenRepo_RevokeByTokenHash_Call {
	return &MockRefreshTokenRepo_RevokeByTokenHash_Call{Call: _e.mock.On("RevokeByTokenHash", ctx, token)}
}

func (_c *MockRefreshTokenRepo_RevokeByTokenHash_Call) Run(run func(ctx context.Context, token string)) *MockRefreshTokenRepo_RevokeByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_RevokeByTokenHash_Call) Return(err error) *MockRefreshTokenRepo_RevokeByTokenHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepo_RevokeByTokenHash_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockRefreshTokenRepo_RevokeByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) Save(ctx context.Context, token *domain.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRefreshTokenRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenRepo_Expecter) Save(ctx interface{}, token interface{}) *MockRefreshTokenRepo_Save_Call {
	return &MockRefreshTokenRepo_Save_Call{Call: _e.mock.On("Save", ctx, token)}
}

func (_c *MockRefreshTokenRepo_Save_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*domain.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_Save_Call) Return(err error) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepo_Save_Call) RunAndReturn(run func(ctx context.Context, token *domain.RefreshToken) error) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
