// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/deimossy/order-processing-system/internal/user/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositories creates a new instance of MockRepositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositories {
	mock := &MockRepositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositories is an autogenerated mock type for the Repositories type
type MockRepositories struct {
	mock.Mock
}

type MockRepositories_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositories) EXPECT() *MockRepositories_Expecter {
	return &MockRepositories_Expecter{mock: &_m.Mock}
}

// RefreshTokenRepo provides a mock function for the type MockRepositories
func (_mock *MockRepositories) RefreshTokenRepo() usecase.RefreshTokenRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokenRepo")
	}

	var r0 usecase.RefreshTokenRepo
	if returnFunc, ok := ret.Get(0).(func() usecase.RefreshTokenRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.RefreshTokenRepo)
		}
	}
	return r0
}

// MockRepositories_RefreshTokenRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokenRepo'
type MockRepositories_RefreshTokenRepo_Call struct {
	*mock.Call
}

// RefreshTokenRepo is a helper method to define mock.On call
func (_e *MockRepositories_Expecter) RefreshTokenRepo() *MockRepositories_RefreshTokenRepo_Call {
	return &MockRepositories_RefreshTokenRepo_Call{Call: _e.mock.On("RefreshTokenRepo")}
}

func (_c *MockRepositories_RefreshTokenRepo_Call) Run(run func()) *MockRepositories_RefreshTokenRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositories_RefreshTokenRepo_Call) Return(refreshTokenRepo usecase.RefreshTokenRepo) *MockRepositories_RefreshTokenRepo_Call {
	_c.Call.Return(refreshTokenRepo)
	return _c
}

func (_c *MockRepositories_RefreshTokenRepo_Call) RunAndReturn(run func() usecase.RefreshTokenRepo) *MockRepositories_RefreshTokenRepo_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepo provides a mock function for the type MockRepositories
func (_mock *MockRepositories) UserRepo() usecase.UserRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepo")
	}

	var r0 usecase.UserRepo
	if returnFunc, ok := ret.Get(0).(func() usecase.UserRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.UserRepo)
		}
	}
	return r0
}

// MockRepositories_UserRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepo'
type MockRepositories_UserRepo_Call struct {
	*mock.Call
}

// UserRepo is a helper method to define mock.On call
func (_e *MockRepositories_Expecter) UserRepo() *MockRepositories_UserRepo_Call {
	return &MockRepositories_UserRepo_Call{Call: _e.mock.On("UserRepo")}
}

func (_c *MockRepositories_UserRepo_Call) Run(run func()) *MockRepositories_UserRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositories_UserRepo_Call) Return(userRepo usecase.UserRepo) *MockRepositories_UserRepo_Call {
	_c.Call.Return(userRepo)
	return _c
}

func (_c *MockRepositories_UserRepo_Call) RunAndReturn(run func() usecase.UserRepo) *MockRepositories_UserRepo_Call {
	_c.Call.Return(run)
	return _c
}
